### ISSUE TITLE
Ubuntu 14.042 AMI doesn't exit anymore

### ISSUE THREAD

**Issue by kimh** [circleci/image-builder-prototype#2]
https://github.com/circleci/image-builder-prototype/blob/master/Vagrantfile#L25 doesn't seem to exit anymore.

**Comment by mcansky** [comment]
exit -> exist ?

**Comment by kimh** [comment]
Oops, yeah that a typo. The issue is already fixed in https://github.com/circleci/image-builder-prototype/pull/5
